### ISSUE TITLE
[OP] Criar Testes Unitários para a Feature de Cadastro

### ISSUE THREAD

**Issue by romeuborges19** [romeuborges19/projeto_barberease#13]
### **Descrição:**

Devem ser desenvolvidos testes unitários para verificar a regularidade dos processos envolvidos no cadastro.

**Tarefas:**

- [x] Desenvolver testes para Models
- [x] Desenvolver testes para Forms
- [x] Desenvolver testes para URLs

**Comment by beneX90** [comment]
Localizadas no app 'barbearia', na pasta 'tests'
